baseURL = 'https://a.ry0.org/'
languageCode = 'en-us'
title = 'Projects and Posts'
theme = "ananke"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
	
[params]
  author = "ry0kc"
  description = "Projects and adjacent posts"
  bitcoin_address = "bc1qexampleyourbtcaddress"

[[menu.main]]
 identifier = "home"
 name = "Home"
 url = "/"
 weight = 1

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Donate"
  url = "/donate/"
  weight = 10  
  
[markup.goldmark.renderer]
  unsafe = true