baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Expansion Base'
theme = "ananke"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
	
[params]
  author = "ry0kc"
  description = "Testing expanding functions"
