baseURL = 'https://t.ry0.or/'
languageCode = 'en-us'
title = 'Expansion Base'
theme = "ananke"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
	
[params]
  author = "ry0kc"
  description = "Testing expanding functions"

[[menu.main]]
 identifier = "home"
 name = "Home"
 url = "/"
 weight = 1

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 3
  
[markup.goldmark.renderer]
  unsafe = true